content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/content/posts'
    view:
      fields: [ title, description, pubDate, image, tags ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Date
        type: date
      - name: image
        label: Image
        type: string
      - name: tags
        label: Tags
        type: string
        list:
          collapsible: false
      - name: body
        label: Body
        type: rich-text